### ISSUE TITLE
Issue encountered while running Terraform

### ISSUE THREAD

**Issue by thiagorr162** [ritual-net/infernet-deploy#3]
Hello team,

I've been following the [deployment guide](https://docs.ritual.net/infernet/node/deployment) to deploy a node using AWS on an Ubuntu environment. However, when attempting to execute Terraform using the command 

`
make init provider=aws
`

 I'm encountering the following error:

`/bin/sh: 1: [[: not found
`

As a beginner in Linux, I acknowledge that my knowledge might be limited, so I apologize if this issue is basic. It seems that the script is attempting to execute using sh instead of bash. I managed to work around this issue by adding the line 

`SHELL := /bin/bash`

 at the beginning of the `procure/Makefile`.

Thank you in advance for your assistance!

**Comment by stelios-ritual** [comment]
@thiagorr162 Thanks for flagging, will include in next minor release.
